USE [CooperativaBD]
GO

/****** Object:  Table [dbo].[CORREO_ELECTRONICO]    Script Date: 22/09/2017 10:58:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CORREO_ELECTRONICO](
	[DIRECCION_CORREO] [nvarchar](100) NOT NULL,
	[CODIGO_EMPLEADO] [bigint] NOT NULL,
 CONSTRAINT [PK_CORREO_ELECTRONICO] PRIMARY KEY CLUSTERED 
(
	[DIRECCION_CORREO] ASC,
	[CODIGO_EMPLEADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CORREO_ELECTRONICO]  WITH CHECK ADD  CONSTRAINT [CORREO_ELECTRONICO_EMPLEADO] FOREIGN KEY([CODIGO_EMPLEADO])
REFERENCES [dbo].[EMPLEADO] ([CODIGO_EMPLEADO])
GO

ALTER TABLE [dbo].[CORREO_ELECTRONICO] CHECK CONSTRAINT [CORREO_ELECTRONICO_EMPLEADO]
GO


