USE [CooperativaBD]
GO

/****** Object:  Table [dbo].[CUENTA_ABONO]    Script Date: 22/09/2017 10:59:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CUENTA_ABONO](
	[NUMERO_CUENTA] [nvarchar](20) NOT NULL,
	[CODIGO_ABONO] [nvarchar](30) NOT NULL,
 CONSTRAINT [PK_CUENTA_ABONO] PRIMARY KEY CLUSTERED 
(
	[NUMERO_CUENTA] ASC,
	[CODIGO_ABONO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CUENTA_ABONO]  WITH CHECK ADD  CONSTRAINT [ABONO_CUENTA_CUENTA] FOREIGN KEY([NUMERO_CUENTA])
REFERENCES [dbo].[CUENTA] ([NUMERO_CUENTA])
GO

ALTER TABLE [dbo].[CUENTA_ABONO] CHECK CONSTRAINT [ABONO_CUENTA_CUENTA]
GO

ALTER TABLE [dbo].[CUENTA_ABONO]  WITH CHECK ADD  CONSTRAINT [CUENTA_ABONO_ABONO] FOREIGN KEY([CODIGO_ABONO])
REFERENCES [dbo].[ABONO] ([CODIGO_ABONO])
GO

ALTER TABLE [dbo].[CUENTA_ABONO] CHECK CONSTRAINT [CUENTA_ABONO_ABONO]
GO


