USE [CooperativaBD]
GO

/****** Object:  Table [dbo].[EMPLEADO]    Script Date: 22/09/2017 10:59:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EMPLEADO](
	[CODIGO_EMPLEADO] [bigint] NOT NULL,
	[PRIMER_NOMBRE] [varchar](20) NULL,
	[SEGUNDO_NOMBRE] [varchar](20) NULL,
	[PRIMER_APELLIDO] [varchar](20) NULL,
	[SEGUNDO_APELLIDO] [varchar](20) NULL,
	[CALLE] [nvarchar](20) NULL,
	[AVENIDA] [nvarchar](20) NULL,
	[NUMERO_CASA] [nvarchar](5) NULL,
	[CIUDAD] [nvarchar](20) NULL,
	[DEPARTAMENTO] [nvarchar](20) NULL,
	[REFERENCIA] [nvarchar](50) NULL,
	[FECHA_NACIMIENTO] [date] NULL,
	[FECHA_CONTRATACION] [date] NULL,
	[FECHA_CREACION] [datetime] NULL,
	[FECHA_MODIF] [datetime] NULL,
	[CREADO_POR] [nvarchar](50) NULL,
	[MODIFICADO_POR] [nvarchar](50) NULL,
 CONSTRAINT [PK_EMPLEADO] PRIMARY KEY CLUSTERED 
(
	[CODIGO_EMPLEADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


