USE [CooperativaBD]
GO

/****** Object:  Table [dbo].[GANANCIA]    Script Date: 22/09/2017 10:59:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GANANCIA](
	[ID_GANANCIA] [nvarchar](50) NOT NULL,
	[CODIGO_EMPLEADO] [bigint] NULL,
	[FECHA_REGISTRO] [date] NULL,
	[GANANCIA] [decimal](10, 2) NULL,
	[STATUS] [nvarchar](30) NULL,
 CONSTRAINT [PK_GANANCIA_1] PRIMARY KEY CLUSTERED 
(
	[ID_GANANCIA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GANANCIA]  WITH CHECK ADD  CONSTRAINT [FK_GANANCIA_EMPLEADO] FOREIGN KEY([CODIGO_EMPLEADO])
REFERENCES [dbo].[EMPLEADO] ([CODIGO_EMPLEADO])
GO

ALTER TABLE [dbo].[GANANCIA] CHECK CONSTRAINT [FK_GANANCIA_EMPLEADO]
GO


