USE [CooperativaBD]
GO

/****** Object:  Table [dbo].[INFO_PRESTAMO]    Script Date: 22/09/2017 11:00:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INFO_PRESTAMO](
	[TIPO_PRESTAMO] [nvarchar](30) NOT NULL,
	[MONTO_MAXIMO] [decimal](10, 2) NOT NULL,
	[TASA_INTERES] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_INFO_PRESTAMO] PRIMARY KEY CLUSTERED 
(
	[TIPO_PRESTAMO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


