USE [CooperativaBD]
GO

/****** Object:  Table [dbo].[PAGO]    Script Date: 22/09/2017 11:00:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PAGO](
	[NUMERO_PAGO] [nvarchar](20) NOT NULL,
	[NUMERO_PRESTAMO] [nvarchar](20) NOT NULL,
	[FECHA_PAGO] [date] NULL,
	[MONTO_PAGADO] [decimal](10, 2) NULL,
	[INTERES_PAGADO] [decimal](10, 2) NULL,
	[CAPITAL_PAGADO] [decimal](10, 2) NULL,
	[FECHA_CREACION] [datetime] NULL,
	[FECHA_MODIF] [datetime] NULL,
	[CREADO_POR] [nvarchar](50) NULL,
	[MODIFICADO_POR] [nvarchar](50) NULL,
 CONSTRAINT [PK_PAGO_1] PRIMARY KEY CLUSTERED 
(
	[NUMERO_PAGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


