USE [CooperativaBD]
GO

/****** Object:  Table [dbo].[PRESTAMO_PAGO]    Script Date: 22/09/2017 11:01:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRESTAMO_PAGO](
	[NUMERO_PRESTAMO] [bigint] NOT NULL,
	[NUMERO_PAGO] [bigint] NOT NULL,
 CONSTRAINT [PK_PRESTAMO_PAGO] PRIMARY KEY CLUSTERED 
(
	[NUMERO_PAGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


