USE [CooperativaBD]
GO

/****** Object:  Table [dbo].[PRESTAMO]    Script Date: 22/09/2017 11:01:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRESTAMO](
	[NUMERO_PRESTAMO] [nvarchar](20) NOT NULL,
	[CODIGO_EMPLEADO] [bigint] NOT NULL,
	[FECHA_PRESTAMO] [date] NULL,
	[TIPO_PRESTAMO] [nvarchar](30) NULL,
	[MONTO_PRESTAMO] [decimal](10, 2) NULL,
	[PERIODOS_PRESTAMO] [int] NULL,
	[NUMERO_PERIODO] [int] NULL,
	[CUOTA_MENSUAL] [decimal](10, 2) NULL,
	[SALDO_PRESTAMO] [decimal](10, 2) NOT NULL,
	[FECHA_CREACION] [datetime] NULL,
	[FECHA_MODIF] [datetime] NULL,
	[CREADO_POR] [nvarchar](50) NULL,
	[MODIFICADO_POR] [nvarchar](50) NULL,
 CONSTRAINT [PK_PRESTAMO] PRIMARY KEY CLUSTERED 
(
	[NUMERO_PRESTAMO] ASC,
	[CODIGO_EMPLEADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRESTAMO]  WITH CHECK ADD  CONSTRAINT [FK_PRESTAMO_INFO_PRESTAMO] FOREIGN KEY([TIPO_PRESTAMO])
REFERENCES [dbo].[INFO_PRESTAMO] ([TIPO_PRESTAMO])
GO

ALTER TABLE [dbo].[PRESTAMO] CHECK CONSTRAINT [FK_PRESTAMO_INFO_PRESTAMO]
GO

ALTER TABLE [dbo].[PRESTAMO]  WITH CHECK ADD  CONSTRAINT [PRESTAMO_EMPLEADO] FOREIGN KEY([CODIGO_EMPLEADO])
REFERENCES [dbo].[EMPLEADO] ([CODIGO_EMPLEADO])
GO

ALTER TABLE [dbo].[PRESTAMO] CHECK CONSTRAINT [PRESTAMO_EMPLEADO]
GO


