USE [CooperativaBD]
GO

/****** Object:  Table [dbo].[PRIVILEGIO]    Script Date: 22/09/2017 11:02:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRIVILEGIO](
	[ID_PRIVILEGIO] [nvarchar](20) NOT NULL,
	[ID_ROL] [nvarchar](20) NULL,
	[DESCRIPCION] [nvarchar](50) NULL,
 CONSTRAINT [PK_PRIVILEGIO] PRIMARY KEY CLUSTERED 
(
	[ID_PRIVILEGIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


