USE [CooperativaBD]
GO

/****** Object:  Table [dbo].[TELEFONO]    Script Date: 22/09/2017 11:02:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TELEFONO](
	[CODIGO_EMPLEADO] [bigint] NOT NULL,
	[TELEFONO_EMPLEADO] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_TELEFONO] PRIMARY KEY CLUSTERED 
(
	[CODIGO_EMPLEADO] ASC,
	[TELEFONO_EMPLEADO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TELEFONO]  WITH CHECK ADD  CONSTRAINT [TELEFONO_EMPLEADO] FOREIGN KEY([CODIGO_EMPLEADO])
REFERENCES [dbo].[EMPLEADO] ([CODIGO_EMPLEADO])
GO

ALTER TABLE [dbo].[TELEFONO] CHECK CONSTRAINT [TELEFONO_EMPLEADO]
GO


