USE [CooperativaBD]
GO

/****** Object:  StoredProcedure [dbo].[SP_CIERRE_MENSUAL]    Script Date: 22/09/2017 13:33:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_CIERRE_MENSUAL] 
	-- Add the parameters for the stored procedure here
	@MODIF_POR NVARCHAR(30)
AS
	DECLARE
		@VAR_TOTAL_APORTACIONES DECIMAL(10,2),
		@VAR_TOTAL_INTERESES DECIMAL(10,2)
BEGIN
	/*DECLARE
		@NUMERO_CUENTA NVARCHAR(30), 
		@AHORRO_MENSUAL DECIMAL(10,2),
		@SALDO_CUENTA DECIMAL(10,2)
	DECLARE
		CURSOR_CUENTAS CURSOR FAST_FORWARD FOR
		SELECT NUMERO_CUENTA, AHORRO_MENSUAL, SALDO_CUENTA FROM dbo.CUENTA FOR READ ONLY
	OPEN CURSOR_CUENTAS

	
	FETCH NEXT FROM CURSOR_CUENTAS INTO @NUMERO_CUENTA, @AHORRO_MENSUAL, @SALDO_CUENTA
	
	WHILE @@FETCH_STATUS = 0
	BEGIN
		--TODO ANTES DEL FETCH
		SET @VAR_TOTAL_INTERESES += @SALDO_CUENTA
		EXEC SP_CUENTA_UPDATE @NUMERO_CUENTA, @MODIF_POR
		EXEC SP_ABONO_CREATE @NUMERO_CUENTA, @AHORRO_MENSUAL, @MODIF_POR
		FETCH NEXT FROM CURSOR_CUENTAS INTO @NUMERO_CUENTA, @AHORRO_MENSUAL, @SALDO_CUENTA
	END	
	CLOSE CURSOR_CUENTAS
	DEALLOCATE CURSOR_CUENTAS*/

	DECLARE
		@NUMERO_PRESTAMO NVARCHAR(30),
		@MONTO_PAGADO DECIMAL(10,2),
		@SALDO_PRESTAMO DECIMAL(10,2),
		@TIPO_PRESTAMO NVARCHAR(30),
		@PER INT,
		@NPER INT,
		@CREADO_POR NVARCHAR(50),
		@STATUS INT
	DECLARE
		CURSOR_PRESTAMOS CURSOR FAST_FORWARD FOR
		SELECT NUMERO_PRESTAMO, MONTO_PRESTAMO, SALDO_PRESTAMO, TIPO_PRESTAMO, PERIODOS_PRESTAMO, NUMERO_PERIODO 
		FROM dbo.PRESTAMO FOR READ ONLY
	OPEN CURSOR_PRESTAMOS
		

	FETCH NEXT FROM CURSOR_PRESTAMOS INTO @NUMERO_PRESTAMO, @MONTO_PAGADO, @SALDO_PRESTAMO, @TIPO_PRESTAMO, @NPER, @PER
	WHILE @@FETCH_STATUS = 0
	BEGIN
		SET @VAR_TOTAL_APORTACIONES += @VAR_TOTAL_INTERESES
		EXEC SP_PRESTAMO_UPDATE @NUMERO_PRESTAMO, @CREADO_POR
		EXEC SP_PAGO_CREATE @NUMERO_PRESTAMO, @MONTO_PAGADO, @TIPO_PRESTAMO, @PER, @NPER, @CREADO_POR, @STATUS
		FETCH NEXT FROM CURSOR_PRESTAMOS INTO @NUMERO_PRESTAMO, @MONTO_PAGADO, @SALDO_PRESTAMO, @TIPO_PRESTAMO, @NPER, @PER
	END
	CLOSE CURSOR_PRESTAMOS
	DEALLOCATE CURSOR_PRESTAMOS

	/*DECLARE
		@VAR_CODIGO_EMPLEADO BIGINT
	DECLARE
		CURSOR_GANANCIAS CURSOR FAST_FORWARD FOR
		SELECT CODIGO_EMPLEADO, GANANCIA FROM dbo.GANANCIA FOR READ ONLY
	OPEN CURSOR_GANANCIAS

	SET @VAR_CODIGO_EMPLEADO = (SELECT CODIGO_EMPLEADO FROM dbo.CUENTA WHERE NUMERO_CUENTA = @NUMERO_CUENTA AND TIPO_CUENTA = 'APORTACION') 
	FETCH NEXT FROM CURSOR_GANANCIAS INTO @VAR_CODIGO_EMPLEADO
	
	WHILE @@FETCH_STATUS = 0
	BEGIN
		 
		 
	END*/
		 

	--SET @VAR_CANT_CUENTAS = (SELECT COUNT(NUMERO_CUENTA) FROM CUENTA)
END
GO


