USE [CooperativaBD]
GO

/****** Object:  StoredProcedure [dbo].[SP_CUENTA_CREATE]    Script Date: 22/09/2017 13:34:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_CUENTA_CREATE] 
(
	@CODIGO_EMPLEADO BIGINT, @TIPO_CUENTA NVARCHAR(50),
	@AHORRO_MENSUAL DECIMAL(10,2), @CREADO_POR NVARCHAR(20)
)
AS
	DECLARE
		@VAR_GET_NUMERO_CUENTA NVARCHAR(20),
		@VAR_FECHA_APERTURA DATE,
		@VAR_SALDO_CUENTA DECIMAL(10,2)
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

	SET @VAR_GET_NUMERO_CUENTA = 'CNT-'+CAST(NEXT VALUE FOR SQ_CUENTA_NUMERO_CUENTA AS NVARCHAR)
	SET @VAR_FECHA_APERTURA = SYSDATETIME()
	SET @VAR_SALDO_CUENTA = 0.00

	INSERT INTO CUENTA(NUMERO_CUENTA, CODIGO_EMPLEADO, TIPO_CUENTA, FECHA_APERTURA, AHORRO_MENSUAL, ANTIGUEDAD,
		SALDO_CUENTA, FECHA_CREACION, CREADO_POR)
	VALUES (@VAR_GET_NUMERO_CUENTA, @CODIGO_EMPLEADO, @TIPO_CUENTA, @VAR_FECHA_APERTURA, @AHORRO_MENSUAL,
	DATEDIFF(DAY, @VAR_FECHA_APERTURA, SYSDATETIME()), @VAR_SALDO_CUENTA, GETDATE(), @CREADO_POR)

    -- Insert statements for procedure here

END
GO


