USE [CooperativaBD]
GO

/****** Object:  StoredProcedure [dbo].[SP_EMPLEADO_CREATE]    Script Date: 22/09/2017 13:35:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_EMPLEADO_CREATE]
( 
	-- Add the parameters for the stored procedure here
	--@CODIGO_EMPLEADO BIGINT,
	@PRIMER_NOMBRE NVARCHAR(20), @SEGUNDO_NOMBRE NVARCHAR(20),
	@PRIMER_APELLIDO NVARCHAR(20), @SEGUNDO_APELLIDO NVARCHAR(20),
	@CALLE NVARCHAR(20), @AVENIDA NVARCHAR(20), @NUMERO_CASA NVARCHAR(5),
	@CIUDAD NVARCHAR(20), @DEPARTAMENTO NVARCHAR(20), @REFERENCIA NVARCHAR(50),
	@FECHA_NACIMIENTO DATE, @FECHA_CONTRATACION DATE, @ID_USUARIO NVARCHAR(20),
	@CONTRASEÑA NVARCHAR(20), @TIPO_ROL NVARCHAR(20), @MONTO_AHORRO DECIMAL(10,2), @MONTO_APORTACION DECIMAL(10,2), @CREADO_POR NVARCHAR(50)
)
AS
	DECLARE
	 @VAR_GET_CODIGO_EMPLEADO NVARCHAR(20)
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
	SET @VAR_GET_CODIGO_EMPLEADO = NEXT VALUE FOR SQ_EMPLEADO__CODIGO
	INSERT INTO DBO.EMPLEADO(CODIGO_EMPLEADO,PRIMER_NOMBRE, SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO, 
	CALLE, AVENIDA, NUMERO_CASA, CIUDAD, DEPARTAMENTO, REFERENCIA, FECHA_NACIMIENTO, FECHA_CONTRATACION,
	FECHA_CREACION, FECHA_MODIF, CREADO_POR)
	VALUES (@VAR_GET_CODIGO_EMPLEADO, @PRIMER_NOMBRE, @SEGUNDO_NOMBRE, @PRIMER_APELLIDO, @SEGUNDO_APELLIDO,
	@CALLE, @AVENIDA, @NUMERO_CASA, @CIUDAD, @DEPARTAMENTO, @REFERENCIA, @FECHA_NACIMIENTO, @FECHA_CONTRATACION,
	GETDATE(), NULL, @CREADO_POR);

	EXEC SP_USUARIO_CREATE @ID_USUARIO, @VAR_GET_CODIGO_EMPLEADO, @CONTRASEÑA, @TIPO_ROL, @CREADO_POR
	EXEC SP_CUENTA_CREATE @VAR_GET_CODIGO_EMPLEADO, 'APORTACION', @MONTO_APORTACION, @CREADO_POR
	EXEC SP_CUENTA_CREATE @VAR_GET_CODIGO_EMPLEADO, 'AHORRO', @MONTO_AHORRO, @CREADO_POR
END
GO


