USE [CooperativaBD]
GO

/****** Object:  StoredProcedure [dbo].[SP_GANANCIA_CREATE]    Script Date: 22/09/2017 13:37:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_GANANCIA_CREATE] 
	-- Add the parameters for the stored procedure here
AS
BEGIN
	DECLARE
		@PORCENTAJE_PARTICIPACION DECIMAL(5,4), 
		@NUMERO_CUENTA NVARCHAR(20),
		@CODIGO_EMPLEADO BIGINT,
		@TOTAL_APORTACIONES DECIMAL(10,2),
		@TOTAL_GANANCIA DECIMAL(10,2),
		@GANANCIA_INDIVIDUAL DECIMAL(10,2)
	DECLARE
		CURSOR_CUENTAS CURSOR FAST_FORWARD FOR
		SELECT NUMERO_CUENTA, CODIGO_EMPLEADO FROM CUENTA where TIPO_CUENTA = 'APORTACION' FOR READ ONLY
	OPEN CURSOR_CUENTAS

	SET @TOTAL_APORTACIONES = (select sum(SALDO_CUENTA) from cuenta where TIPO_CUENTA = 'APORTACION')
	SET @TOTAL_GANANCIA = (select SUM((CUOTA_MENSUAL*PERIODOS_PRESTAMO)-MONTO_PRESTAMO)  FROM PRESTAMO 
		WHERE DATEDIFF(MONTH, FECHA_PRESTAMO, SYSDATETIME()) = 1)

	FETCH NEXT FROM CURSOR_CUENTAS INTO @NUMERO_CUENTA, @CODIGO_EMPLEADO
	WHILE @@FETCH_STATUS = 0
	BEGIN
		SET @PORCENTAJE_PARTICIPACION = (select SALDO_CUENTA from cuenta where NUMERO_CUENTA = @NUMERO_CUENTA AND TIPO_CUENTA = 'APORTACION')/@TOTAL_APORTACIONES
		SET @GANANCIA_INDIVIDUAL = @TOTAL_GANANCIA*@PORCENTAJE_PARTICIPACION

		INSERT INTO GANANCIA(ID_GANANCIA, CODIGO_EMPLEADO, FECHA_REGISTRO, GANANCIA)
		VALUES('GN-'+CAST((SELECT DATEPART(MONTH, GETDATE())) AS nvarchar)+'-'+CAST(@CODIGO_EMPLEADO AS NVARCHAR), @CODIGO_EMPLEADO,
		SYSDATETIME(), @GANANCIA_INDIVIDUAL)
		PRINT  @GANANCIA_INDIVIDUAL
		FETCH NEXT FROM CURSOR_CUENTAS INTO @NUMERO_CUENTA, @CODIGO_EMPLEADO
	END
	PRINT  @TOTAL_GANANCIA
	CLOSE CURSOR_CUENTAS
	DEALLOCATE CURSOR_CUENTAS
END
GO


