USE [CooperativaBD]
GO

/****** Object:  StoredProcedure [dbo].[SP_PAGO_CREATE]    Script Date: 22/09/2017 13:37:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
CREATE PROCEDURE [dbo].[SP_PAGO_CREATE] 
(
	@NUMERO_PRESTAMO NVARCHAR(20), @MONTO_PAGADO DECIMAL(10,2),
	@TIPO_PRESTAMO NVARCHAR(20), @PER INT, @NPER INT, @CREADO_POR NVARCHAR(50),
	@STATUS INT OUT
)
AS
	DECLARE
		@VAR_NUMERO_PAGO NVARCHAR(20),
		@VAR_INTERES_PAGADO DECIMAL(10,2),
		@VAR_CAPITAL_PAGADO DECIMAL(10,2),
		@TASA DECIMAL(10,2)
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;
	SET @STATUS = 0

	IF(@TIPO_PRESTAMO = 'FIDUCIARIO')
	BEGIN
		SET @TASA = (SELECT TASA_INTERES FROM dbo.INFO_PRESTAMO WHERE @TIPO_PRESTAMO = TIPO_PRESTAMO)
	END

	IF(@PER > @NPER)
	BEGIN
		SET @STATUS = -1
	END

	IF(@STATUS = 0)
	BEGIN
		SET @VAR_NUMERO_PAGO = 'PG-'+CAST(NEXT VALUE FOR SQ_PAGO_NUMERO_PAGO AS nvarchar)
		EXEC @VAR_INTERES_PAGADO = dbo.FN_PAGO_IPMT @TASA, @PER, @NPER, @MONTO_PAGADO, 0, 0  
		EXEC @VAR_CAPITAL_PAGADO = dbo.FN_PAGO_PPMT @TASA, @PER, @NPER, @MONTO_PAGADO, 0, 0

		INSERT INTO PAGO(NUMERO_PAGO, NUMERO_PRESTAMO, FECHA_PAGO, MONTO_PAGADO, INTERES_PAGADO, CAPITAL_PAGADO, FECHA_CREACION, CREADO_POR)
		VALUES(@VAR_NUMERO_PAGO, @NUMERO_PRESTAMO, SYSDATETIME(), @MONTO_PAGADO, @VAR_INTERES_PAGADO, @VAR_CAPITAL_PAGADO,
		GETDATE(), @CREADO_POR)
	END
	
	-- Insert statements for procedure here
END
GO


